spring.application.name=sprintflow



spring.datasource.url=jdbc:mysql://localhost:3306/sprintflow
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

jwt.secret=7f3c9a21b8e54d6c92a17f04e8b63a5d7c91f2e6a84b0c53d91e7f26a3b85c19